### ISSUE TITLE
Unhandled ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by judwhite** [judwhite/NsqSharp#21]
Check internal uses of NsqSharp.Utils.GoFunc, possibly timers

Exception Info: System.ArgumentOutOfRangeException
Stack:
   at NsqSharp.Utils.GoFunc+<>c__DisplayClass1.<Run>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by judwhite** [comment]
appears to be fixed in 0.5.0-beta1
