### ISSUE TITLE
ObjectDisposedException during network error

### ISSUE THREAD

**Issue by judwhite** [judwhite/NsqSharp#45]
[2016-05-14 09:20:00.7733] [Error] C7 IO error - System.ArgumentException: length of response is too small
Parameter name: response
   at NsqSharp.Core.Protocol.UnpackResponse(Byte[] response, FrameType& frameType, Byte[]& body) in d:\Projects_github\NsqSharp\NsqSharp\Core\Protocol.cs:line 104
   at NsqSharp.Core.Conn.readLoop() in d:\Projects_github\NsqSharp\NsqSharp\Core\Conn.cs:line 554

[2016-05-14 09:20:09.9268] [Error] C7 IO error - System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at NsqSharp.Utils.TcpConn.Write(Byte[] b, Int32 offset, Int32 length) in d:\Projects_github\NsqSharp\NsqSharp\Utils\TcpConn.cs:line 127
   at NsqSharp.Core.Command.WriteTo(IWriter w, Byte[] buf) in d:\Projects_github\NsqSharp\NsqSharp\Core\Command.cs:line 164
   at NsqSharp.Core.Conn.WriteCommand(Command cmd) in d:\Projects_github\NsqSharp\NsqSharp\Core\Conn.cs:line 344

[2016-05-14 09:20:09.9268] [Error] C7 
error sending CLS - System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at NsqSharp.Utils.TcpConn.Write(Byte[] b, Int32 offset, Int32 length) in d:\Projects_github\NsqSharp\NsqSharp\Utils\TcpConn.cs:line 127
   at NsqSharp.Core.Command.WriteTo(IWriter w, Byte[] buf) in d:\Projects_github\NsqSharp\NsqSharp\Core\Command.cs:line 164
   at NsqSharp.Core.Conn.WriteCommand(Command cmd) in d:\Projects_github\NsqSharp\NsqSharp\Core\Conn.cs:line 351
   **at NsqSharp.Consumer.StopAsync() in d:\Projects_github\NsqSharp\NsqSharp\Consumer.cs:line 1528**

[2016-08-12 16:12:38.6065] [Error] C12 error sending command REQ 0a8fa0dcac598001 90000 - System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at NsqSharp.Utils.TcpConn.Write(Byte[] b, Int32 offset, Int32 length) in d:\Projects_github\NsqSharp\NsqSharp\Utils\TcpConn.cs:line 127
   at NsqSharp.Core.Command.WriteTo(IWriter w, Byte[] buf) in d:\Projects_github\NsqSharp\NsqSharp\Core\Command.cs:line 164
   at NsqSharp.Core.Conn.WriteCommand(Command cmd) in d:\Projects_github\NsqSharp\NsqSharp\Core\Conn.cs:line 351
   **at NsqSharp.Core.Conn.&lt;writeLoop>b__2(msgResponse resp) in** d:\Projects_github\NsqSharp\NsqSharp\Core\Conn.cs:line 705

**Comment by judwhite** [comment]
Most likely caused by a call to `Write` after `Close`
